In [1]:
print("Hi")

Hi

In [2]:
# Check if required libraries are installed

import importlib.util

required_libraries = ["numpy", "pandas"]

for library in required_libraries:
    if importlib.util.find_spec(library) is not None:
        print(f"✅ {library} is installed")
    else:
        print(f"❌ {library} is NOT installed")

✅ numpy is installed
✅ pandas is installed

In [3]:
import numpy as np
import pandas as pd

print("✅ NumPy and Pandas imported successfully")
print("NumPy version:", np.__version__)
print("Pandas version:", pd.__version__)

✅ NumPy and Pandas imported successfully
NumPy version: 2.4.4
Pandas version: 3.0.2

In [5]:
orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
customers = pd.read_csv("olist_customers_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")
reviews = pd.read_csv("olist_order_reviews_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
geolocation = pd.read_csv("olist_geolocation_dataset.csv")
category_translation = pd.read_csv("product_category_name_translation.csv")

print("All Olist datasets loaded successfully")

All Olist datasets loaded successfully

In [6]:
# Check shape of each dataset

datasets = {
    "orders": orders,
    "order_items": order_items,
    "customers": customers,
    "products": products,
    "payments": payments,
    "reviews": reviews,
    "sellers": sellers,
    "geolocation": geolocation,
    "category_translation": category_translation
}

for name, df in datasets.items():
    print(f"{name}: {df.shape[0]} rows, {df.shape[1]} columns")

orders: 99441 rows, 8 columns
order_items: 112650 rows, 7 columns
customers: 99441 rows, 5 columns
products: 32951 rows, 9 columns
payments: 103886 rows, 5 columns
reviews: 99224 rows, 7 columns
sellers: 3095 rows, 4 columns
geolocation: 1000163 rows, 5 columns
category_translation: 71 rows, 2 columns

In [7]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [8]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [9]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [10]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [11]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [13]:
#Check column names of all tables
for name, df in datasets.items():
    print(f"\n===== {name.upper()} =====")
    print(df.columns.tolist())

===== ORDERS =====
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

===== ORDER_ITEMS =====
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

===== CUSTOMERS =====
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

===== PRODUCTS =====
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

===== PAYMENTS =====
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

===== REVIEWS =====
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

===== SELLERS =====
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

===== GEOLOCATION =====
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

===== CATEGORY_TRANSLATION =====
['product_category_name', 'product_category_name_english']

In [20]:
# Convert timestamp columns in orders table

date_columns_orders = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns_orders:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

print(" Orders date columns converted successfully")

 Orders date columns converted successfully

In [21]:
print("Minimum order purchase date:", orders["order_purchase_timestamp"].min())
print("Maximum order purchase date:", orders["order_purchase_timestamp"].max())

Minimum order purchase date: 2016-09-04 21:15:19
Maximum order purchase date: 2018-10-17 17:30:18

In [22]:
# Null value check

for name, df in datasets.items():
    print(f"\n===== NULL VALUES IN {name.upper()} =====")
    print(df.isnull().sum())

===== NULL VALUES IN ORDERS =====
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

===== NULL VALUES IN ORDER_ITEMS =====
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

===== NULL VALUES IN CUSTOMERS =====
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

===== NULL VALUES IN PRODUCTS =====
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

===== NULL VALUES IN PAYMENTS =====
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

===== NULL VALUES IN REVIEWS =====
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

===== NULL VALUES IN SELLERS =====
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

===== NULL VALUES IN GEOLOCATION =====
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

===== NULL VALUES IN CATEGORY_TRANSLATION =====
product_category_name            0
product_category_name_english    0
dtype: int64

In [23]:
# Duplicate row check

for name, df in datasets.items():
    duplicate_count = df.duplicated().sum()
    print(f"{name}: {duplicate_count} duplicate rows")

orders: 0 duplicate rows
order_items: 0 duplicate rows
customers: 0 duplicate rows
products: 0 duplicate rows
payments: 0 duplicate rows
reviews: 0 duplicate rows
sellers: 0 duplicate rows
geolocation: 261831 duplicate rows
category_translation: 0 duplicate rows

In [24]:
summary = []

for name, df in datasets.items():
    summary.append({
        "table_name": name,
        "rows": df.shape[0],
        "columns": df.shape[1],
        "duplicate_rows": df.duplicated().sum(),
        "total_null_values": df.isnull().sum().sum()
    })

summary_df = pd.DataFrame(summary)

summary_df

             table_name     rows  columns  duplicate_rows  total_null_values
0                orders    99441        8               0               4908
1           order_items   112650        7               0                  0
2             customers    99441        5               0                  0
3              products    32951        9               0               2448
4              payments   103886        5               0                  0
5               reviews    99224        7               0             145903
6               sellers     3095        4               0                  0
7           geolocation  1000163        5          261831                  0
8  category_translation       71        2               0                  0